//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalArtist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimalArtist()
        {
            this.ArtistPerfomances = new HashSet<ArtistPerfomance>();
        }
    
        public int Id { get; set; }
        public int AnimalId { get; set; }
        public int ArtistId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtistPerfomance> ArtistPerfomances { get; set; }
    }
}
